name: flutter_update_checker
description: Simple package to check update for Android (Google Play, App Gallery, RuStore) and iOS (AppStore)
version: 1.1.0
homepage: https://github.com/adictgroup/flutter_update_checker
repository: https://github.com/adictgroup/flutter_update_checker
issue_tracker: https://github.com/adictgroup/flutter_update_checker/issues

screenshots:
  - description: "flutter_update_checker Logo"
    path: other/docs/images/pub_logo.png

topics:
  - update
  - upgrade
  - app-store
  - google-play
  - rustore
  - app-gallery
  - huawei 
  - harmony-os



environment:
  sdk: '>=3.7.0 <4.0.0'

dependencies:
  dio: ^5.9.0
  flutter:
    sdk: flutter
  in_app_update: ^4.2.5
  package_info_plus: ^9.0.0
  url_launcher: ^6.3.2

dev_dependencies:
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter


platforms:
  android:
  ios: